language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
services:
- docker
before_script: 
script:
- npm i
- npm run build
deploy:
  provider: firebase
  token:
    secure: J5rbnKQlNoxa57qc9l63oEaf4Wja7U9hoi9rZN7o/cOf3ITa7RHNuQtAgl2ZMnST3h/4kJGsoYfKjSKk/GEI8sNL41oAY6OChK55VPz2NhttT2sYX82OVRScahWbpcRe+oxQk3I62q/xuc9eRLBuasOed1v8aONZg/Vf18kRe7n6gV0xfqk94YFIvl4k3V0xEs2KZw2ZvRtkSAvSdhhcmgMCHC4ZP2XG/XWZTnautAi/Iocok9zW/003YmubwVru59W6ZHX5DKRX3MGgMGtEYLo0SLXdQQnRboDNKIRwuVz9dzpqk6fBFK0MMfHVfdutsq+2pC7lcqwkFe0X0aubWr5Rs4vB7H/CTkK+Z/T8cIWlYrJVofxdza7zIBB9Rk8K14diburrlGbS7ByABPFpNiYYjwqqp0OMp8egMURwSGqjfZXlNSFgrwP/Cb1NEy/hc3ThjU+5rWUhE2pmA8UFmAMYSN7y6/AHN+G7Eux88gUoGwCfZzNLyHtcDpgcHo6M4okqVUqbwyFrMVUa7QhGQLSBZv1yMDnR7sV61ejM9xPZ6SbLgEPdcPmRvGLEntjKl+hkdorFBQCnlHHU7hzrjlW6DlYG3mSmLOf4SI5LLSpKfYMy4aDCbig66lY4tDpHjX3hY1FMx++FovDsPjOLmD22SdEHzSd4kstoACN5b3Y=
  local_dir: dist
  skip-cleanup: true
  project: vox-wallet
  keep-history: true
  on:
    branch: master

